---
abstract: 'maintain and search a minimal CPAN database'
author:
  - 'Reini Urban <rurban@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-UnQLite
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Tar: 1.54
  CPAN::DistnameInfo: 0.09
  CPAN::Index: 1.93
  Compress::Zlib: 0
  UnQLite: 0.02
  File::HomeDir: 0
  File::Spec: 0
  IO::Zlib: 0
  LWP::Simple: 0
  parent: 0
version: 0.1
